FROM python:3.10-slim

WORKDIR /app

COPY requirements.mac.txt .
RUN pip install --no-cache-dir -r requirements.mac.txt

COPY main.py .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "info"]

